platform :ios, '13.0'

target 'FCL_Cocoa_Demo' do
  use_frameworks!

  pod 'FCL-SDK', :path => '../../'
  pod 'SnapKit'
  pod 'RxSwift'
  pod 'RxCocoa'
  
  # should be removed
  pod 'FlowSDK', :git => 'git@github.com:portto/flow-swift-sdk.git'
  pod 'Cadence', :git => 'git@github.com:portto/flow-swift-sdk.git'
  pod 'BloctoSDK/Flow', :git => 'https://github.com/portto/blocto-ios-sdk.git', :branch => 'feat/flow'
  pod 'BigInt'

end
